"""initial

Revision ID: 7fbd7d2536c3
Revises: 
Create Date: 2026-02-27 00:02:13.013899

"""

from alembic import op
import sqlalchemy as sa


revision = '7fbd7d2536c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the city.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable city name.'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL-safe city identifier.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('donation_settings',
    sa.Column('id', sa.Integer(), nullable=False, comment='Always 1 – singleton row.'),
    sa.Column('points_per_zloty', sa.Numeric(precision=6, scale=2), nullable=False, comment='Loyalty points awarded per złoty donated by an active member.'),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Minimum accepted donation amount in PLN.'),
    sa.Column('suggested_amounts', sa.Text(), nullable=True, comment='JSON array of suggested donation amounts displayed on the form.'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='When false the donation form is hidden from users.'),
    sa.Column('account_number', sa.String(length=64), nullable=True, comment='Bank account number for manual wire transfers.'),
    sa.Column('payment_title', sa.String(length=200), nullable=True, comment='Default transfer title prefix shown to donors.'),
    sa.Column('bank_owner_name', sa.String(length=200), nullable=True, comment='Account owner name for display on the support page.'),
    sa.Column('bank_owner_address', sa.Text(), nullable=True, comment='Account owner address for display on the support page.'),
    sa.Column('message', sa.Text(), nullable=True, comment='Admin-editable public message shown at the top of the support page.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last settings update.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_types',
    sa.Column('key', sa.String(length=50), nullable=False, comment="Slug key used in Event.event_type, e.g. 'pilka_reczna'."),
    sa.Column('label', sa.String(length=100), nullable=False, comment="Display name shown in UI, e.g. 'Piłka ręczna'."),
    sa.Column('icon_key', sa.String(length=50), nullable=False, comment='Key into the EXTRA_ICONS map on the frontend.'),
    sa.Column('color', sa.String(length=50), nullable=False, comment='Tailwind text-color class used for the icon.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this custom type was created.'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the product.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Product name shown in the catalog.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Long-form product description.'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False, comment='Product price in major currency units.'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='Optional product image URL.'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the product is visible in the catalog.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the product was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the user.'),
    sa.Column('google_id', sa.String(length=255), nullable=True, comment='Google account identifier linked to the user.'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='Optional unique username for password auth.'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Primary email address used for login and contact.'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name shown in the UI and communications.'),
    sa.Column('picture_url', sa.Text(), nullable=True, comment='Avatar image URL from OAuth or user profile.'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hashed password for local auth (nullable for OAuth-only).'),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True, comment='Hashed SHA-256 password-reset token (one-time use).'),
    sa.Column('password_reset_token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Expiry of the current password-reset token.'),
    sa.Column('role', sa.Enum('guest', 'member', 'admin', name='userrole'), nullable=True, comment='Role used for authorization decisions.'),
    sa.Column('account_status', sa.Enum('pending', 'active', 'banned', name='accountstatus'), nullable=True, comment='Approval status of the account.'),
    sa.Column('google_refresh_token', sa.String(length=512), nullable=True, comment='OAuth refresh token for Google Calendar integration.'),
    sa.Column('google_scopes', sa.Text(), nullable=True, comment='OAuth scopes granted by the user.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the user was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the announcement.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short headline for the announcement.'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full body text of the announcement.'),
    sa.Column('author_id', sa.String(length=36), nullable=False, comment='Admin user who created this announcement.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the announcement was created.'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user who submitted approval request.'),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True, comment='International dialling prefix (e.g. +48).'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Phone number without country code.'),
    sa.Column('admin_message', sa.String(length=500), nullable=True, comment='Optional message from user to admin during join request.'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the approval request was submitted.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the comment.'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment="Type of resource this comment belongs to (e.g. 'event')."),
    sa.Column('resource_id', sa.String(length=36), nullable=False, comment='ID of the resource this comment belongs to.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user who wrote this comment.'),
    sa.Column('content', sa.Text(), nullable=False, comment='The comment text content.'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='FK to parent comment for threading (NULL for top-level).'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='Whether this comment is pinned by an admin.'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft-delete flag; deleted comments show placeholder text.'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Optimistic lock version for concurrent edit safety.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the comment was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index('ix_comments_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_resource', 'comments', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_comments_user', 'comments', ['user_id'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the donation.'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='FK to the donating user; null for anonymous donations.'),
    sa.Column('donor_name', sa.String(length=100), nullable=True, comment='Optional display name provided by the donor.'),
    sa.Column('donor_email', sa.String(length=255), nullable=True, comment='Optional contact e-mail provided by the donor.'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Declared donation amount in PLN.'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='ISO currency code, always PLN for now.'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Lifecycle state of the donation.'),
    sa.Column('transfer_reference', sa.String(length=64), nullable=False, comment='Unique bank transfer title that the donor must include in the wire.'),
    sa.Column('points_awarded', sa.Integer(), nullable=True, comment='Loyalty points awarded to the member after confirmation; null if not applicable.'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='Optional internal note added by admin during confirmation/cancellation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the donation record was created.'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the admin confirmed receipt of the transfer.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_index(op.f('ix_donations_transfer_reference'), 'donations', ['transfer_reference'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the event.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short title displayed in listings.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Long-form event description shown in details view.'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Category tag for filtering (e.g., karate, mors).'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False, comment='Start datetime of the event occurrence.'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='Optional end datetime for multi-hour events.'),
    sa.Column('time_info', sa.String(length=100), nullable=True, comment='Free-form time window (e.g. 19:30-21:00).'),
    sa.Column('features', sa.JSON(), nullable=True, comment='Optional list of feature labels for UI display.'),
    sa.Column('payment_info', sa.Text(), nullable=True, comment='Additional payment details shown to users.'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City name for display and fallback filtering.'),
    sa.Column('city_id', sa.String(length=36), nullable=True, comment='Optional FK to normalized City record.'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Specific location or venue name.'),
    sa.Column('show_map', sa.Boolean(), nullable=True, comment='Whether the map should be shown in UI.'),
    sa.Column('show_video', sa.Boolean(), nullable=True, comment='Whether the YouTube embed should be shown.'),
    sa.Column('youtube_url', sa.String(length=500), nullable=True, comment='Optional YouTube URL for promo video.'),
    sa.Column('price_guest', sa.Numeric(precision=10, scale=2), nullable=True, comment='Price for non-subscribers.'),
    sa.Column('price_member', sa.Numeric(precision=10, scale=2), nullable=True, comment='Price for active subscribers.'),
    sa.Column('manual_payment_verification', sa.Boolean(), nullable=False, comment='Whether manual payment flow is required.'),
    sa.Column('manual_payment_url', sa.String(length=500), nullable=True, comment='Transfer instructions URL for manual payments.'),
    sa.Column('manual_payment_due_hours', sa.Integer(), nullable=False, comment='Hours until manual payment must be confirmed.'),
    sa.Column('max_participants', sa.Integer(), nullable=True, comment='Maximum confirmed participants; null means unlimited.'),
    sa.Column('is_big_event', sa.Boolean(), nullable=True, comment='Marks events highlighted as large-scale.'),
    sa.Column('requires_subscription', sa.Boolean(), nullable=True, comment='Whether active subscription is required to register.'),
    sa.Column('cancel_cutoff_hours', sa.Integer(), nullable=True, comment='Hours before start when cancellation is allowed.'),
    sa.Column('points_value', sa.Integer(), nullable=True, comment='Points awarded for confirmed participation.'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Optimistic locking version for concurrent registrations.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the event was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user owning the payment method.'),
    sa.Column('card_token', sa.String(length=255), nullable=True, comment='Gateway token referencing stored card details.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the payment method was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the payment.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the owning user.'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='Payment gateway identifier.'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Payment amount in minor currency units.'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='ISO currency code.'),
    sa.Column('payment_type', sa.String(length=20), nullable=False, comment='Type of payment (event or subscription).'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Current payment status.'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Human-readable description for receipts.'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='Serialized JSON metadata for the payment.'),
    sa.Column('gateway_response', sa.Text(), nullable=True, comment='Raw gateway response payload for audits.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the payment was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the payment was completed.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('subscription_purchases',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the subscription purchase.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the purchasing user.'),
    sa.Column('plan_code', sa.String(length=32), nullable=False, comment='Subscription plan code (free, monthly, yearly).'),
    sa.Column('periods', sa.Integer(), nullable=False, comment='Number of billing periods purchased.'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount to pay (plan price * periods).'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code.'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='Current purchase status.'),
    sa.Column('payment_id', sa.String(length=255), nullable=True, comment='External payment ID for manual payment linkage.'),
    sa.Column('manual_payment_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when user declared the manual payment.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the purchase was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_purchases_id'), 'subscription_purchases', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user owning the subscription.'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='Subscription end datetime; null means no active subscription.'),
    sa.Column('points', sa.Integer(), nullable=False, comment='Accumulated loyalty points for the user.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the subscription row was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user owning the profile.'),
    sa.Column('about_me', sa.Text(), nullable=True, comment='Free-form user bio displayed on profile.'),
    sa.Column('interest_tags', sa.Text(), nullable=True, comment='Serialized list of interest tags.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the profile was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comment_reactions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the reaction.'),
    sa.Column('comment_id', sa.String(length=36), nullable=False, comment='FK to the comment being reacted to.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user who reacted.'),
    sa.Column('reaction_type', sa.Enum('like', 'heart', 'laugh', 'wow', 'sad', 'fire', name='reactiontype'), nullable=False, comment='The type of reaction emoji.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the reaction was created.'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', 'reaction_type', name='uq_comment_reaction_user_type')
    )
    op.create_index(op.f('ix_comment_reactions_id'), 'comment_reactions', ['id'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the registration.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the registering user.'),
    sa.Column('event_id', sa.String(length=36), nullable=False, comment='FK to the registered event.'),
    sa.Column('occurrence_date', sa.Date(), nullable=False, comment='Date of the event occurrence for this registration.'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='Current registration status.'),
    sa.Column('payment_id', sa.String(length=255), nullable=True, comment='External payment ID for gateway linkage.'),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True, comment='Google Calendar event identifier.'),
    sa.Column('manual_payment_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when manual payment was declared.'),
    sa.Column('promoted_from_waitlist_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when waitlisted user was promoted.'),
    sa.Column('manual_payment_due_at', sa.DateTime(timezone=True), nullable=True, comment='Deadline for completing manual payment.'),
    sa.Column('waitlist_notification_sent', sa.Boolean(), nullable=False, comment='Whether a waitlist notification was sent.'),
    sa.Column('waitlist_notified_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when waitlist notification was sent.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the registration was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'occurrence_date', name='unique_user_event_occurrence_registration')
    )
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    op.create_table('registration_refund_tasks',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID for the refund task.'),
    sa.Column('registration_id', sa.String(length=36), nullable=False, comment='FK to the cancelled registration.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the user requesting refund.'),
    sa.Column('event_id', sa.String(length=36), nullable=False, comment='FK to the related event.'),
    sa.Column('occurrence_date', sa.Date(), nullable=False, comment='Occurrence date associated with the refund task.'),
    sa.Column('refund_eligible', sa.Boolean(), nullable=False, comment='Computed eligibility for refund.'),
    sa.Column('recommended_should_refund', sa.Boolean(), nullable=False, comment='System recommendation for refund decision.'),
    sa.Column('should_refund', sa.Boolean(), nullable=False, comment='Admin decision to issue refund.'),
    sa.Column('refund_marked_paid', sa.Boolean(), nullable=False, comment='Whether refund was paid out.'),
    sa.Column('override_reason', sa.Text(), nullable=True, comment='Reason for admin override of recommendation.'),
    sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True, comment='FK to admin who reviewed the task.'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when task was reviewed.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the refund task was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update.'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_refund_tasks_event_id'), 'registration_refund_tasks', ['event_id'], unique=False)
    op.create_index(op.f('ix_registration_refund_tasks_id'), 'registration_refund_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_registration_refund_tasks_refund_marked_paid'), 'registration_refund_tasks', ['refund_marked_paid'], unique=False)
    op.create_index(op.f('ix_registration_refund_tasks_registration_id'), 'registration_refund_tasks', ['registration_id'], unique=True)
    op.create_index(op.f('ix_registration_refund_tasks_user_id'), 'registration_refund_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_refund_tasks_user_id'), table_name='registration_refund_tasks')
    op.drop_index(op.f('ix_registration_refund_tasks_registration_id'), table_name='registration_refund_tasks')
    op.drop_index(op.f('ix_registration_refund_tasks_refund_marked_paid'), table_name='registration_refund_tasks')
    op.drop_index(op.f('ix_registration_refund_tasks_id'), table_name='registration_refund_tasks')
    op.drop_index(op.f('ix_registration_refund_tasks_event_id'), table_name='registration_refund_tasks')
    op.drop_table('registration_refund_tasks')
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_comment_reactions_id'), table_name='comment_reactions')
    op.drop_table('comment_reactions')
    op.drop_table('user_profiles')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_purchases_id'), table_name='subscription_purchases')
    op.drop_table('subscription_purchases')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_donations_transfer_reference'), table_name='donations')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index('ix_comments_user', table_name='comments')
    op.drop_index('ix_comments_resource', table_name='comments')
    op.drop_index('ix_comments_parent', table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('approval_requests')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('feedback')
    op.drop_table('event_types')
    op.drop_table('donation_settings')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
