"""make feedback email nullable

Revision ID: 84694e4e5850
Revises: e5f6a7b8c9d0
Create Date: 2026-02-21 12:51:12.376572

"""

from alembic import op
import sqlalchemy as sa


revision = '84694e4e5850'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
