"""add temporary feedback table

Revision ID: da80f277528f
Revises: d4e5f6a7b8c9
Create Date: 2026-02-21 11:49:50.448705

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'da80f277528f'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('subscription_purchases', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Primary key UUID for the subscription purchase.',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to the purchasing user.',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'plan_code',
               existing_type=sa.VARCHAR(length=32),
               comment='Subscription plan code (free, monthly, yearly).',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'periods',
               existing_type=sa.INTEGER(),
               comment='Number of billing periods purchased.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('subscription_purchases', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Total amount to pay (plan price * periods).',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'currency',
               existing_type=sa.VARCHAR(length=3),
               comment='Currency code.',
               existing_nullable=False,
               existing_server_default=sa.text("'PLN'::character varying"))
    op.alter_column('subscription_purchases', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               comment='Current purchase status.',
               existing_server_default=sa.text("'manual_payment_required'::character varying"))
    op.alter_column('subscription_purchases', 'payment_id',
               existing_type=sa.VARCHAR(length=255),
               comment='External payment ID for manual payment linkage.',
               existing_nullable=True)
    op.alter_column('subscription_purchases', 'manual_payment_confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when user declared the manual payment.',
               existing_nullable=True)
    op.alter_column('subscription_purchases', 'is_test_data',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Marks rows created by seed/test tooling.',
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the purchase was created.',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_purchases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the last update.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_purchases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of the last update.',
               existing_nullable=True)
    op.alter_column('subscription_purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the purchase was created.',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_purchases', 'is_test_data',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Marks rows created by seed/test tooling.',
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_purchases', 'manual_payment_confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when user declared the manual payment.',
               existing_nullable=True)
    op.alter_column('subscription_purchases', 'payment_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='External payment ID for manual payment linkage.',
               existing_nullable=True)
    op.alter_column('subscription_purchases', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               comment=None,
               existing_comment='Current purchase status.',
               existing_server_default=sa.text("'manual_payment_required'::character varying"))
    op.alter_column('subscription_purchases', 'currency',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='Currency code.',
               existing_nullable=False,
               existing_server_default=sa.text("'PLN'::character varying"))
    op.alter_column('subscription_purchases', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Total amount to pay (plan price * periods).',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'periods',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of billing periods purchased.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('subscription_purchases', 'plan_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Subscription plan code (free, monthly, yearly).',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK to the purchasing user.',
               existing_nullable=False)
    op.alter_column('subscription_purchases', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Primary key UUID for the subscription purchase.',
               existing_nullable=False)
    op.drop_table('feedback')
    # ### end Alembic commands ###
